server:
  port: 9090

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
  application:
    name: proposta
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  messages:
    basename: i18n/messages
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sys
    username: root
    password: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    enabled: ${RABBIT_ENABLED:true}
    listener:
      simple:
        default-requeue-rejected: false
    template:
      reply-timeout: ${RABBIT_REPLY_TIMEOUT:15000}
